### ISSUE TITLE
Why we have ROADMAP.md?

### ISSUE THREAD

**Issue by zplusfour** [Repl-it-Coders/Repl.it-2020#13]
why we have roadmap.md file
we can just make a roadmap at the `Projects` page!

**Comment by whippingdot** [comment]
Will do that rn..Wait did you do that? I am changing it. It needs to be on the projects page **of this org**

**Comment by zplusfour** [comment]
IT IS ON THIS ORG SMH

**Comment by whippingdot** [comment]
No, it is in this repo. In the org home page you can have a project. Check it out, it is there.

**Comment by zplusfour** [comment]
OH OK IM SORRY FOR CAPS

**Comment by whippingdot** [comment]
THEN Y U USE CAPS AGAIN??

**Comment by iop3** [comment]
LMFAO!!!!!!
