### ISSUE TITLE
How can i join ?

### ISSUE THREAD

**Issue by httpanand** [Repl-it-Coders/Repl.it-2020#18]

**Comment by ghost** [comment]
You need to gain permission from @whippingdot 

> You also need a https://replit.com account which I assume you have.

**Comment by whippingdot** [comment]
I don't think you need a replit account anymore

**Comment by whippingdot** [comment]
@httpanand do you still want to join. Ill send you a request

Also if you have a replit account can you please tell me?

Btw what languages do you code in

**Comment by httpanand** [comment]
@whippingdot Yea i use replit ...

**Comment by whippingdot** [comment]
What is ur replit account username

**Comment by ghost** [comment]
@httpanand is it this perhaps? https://replit.com/@httpanand

**Comment by whippingdot** [comment]
It probably is lol
@httpanand what languages do you program in

**Comment by ghost** [comment]
I bet python is one.

**Comment by httpanand** [comment]
> @httpanand is it this perhaps? https://replit.com/@httpanand

yeah .. thats my new acc .. and [this](https://replit.com/@anandpy2156) is my old one : )

**Comment by httpanand** [comment]
> I bet python is one.



> I bet python is one.

Yeah not so pro ... Python , JS , lua etc.. 😅

**Comment by ghost** [comment]
@httpanand bruh. Lua. I also doe JS (with vue v3) and Python (and css and scss.) Learning rust rn. YOU ARE NOT "not so pro."

**Comment by ghost** [comment]
The reason I said that I bet there is python is because everyone starts out with python, unless you decided to go js first.

**Comment by httpanand** [comment]
> The reason I said that I bet there is python is because everyone starts out with python, unless you decided to go js first.

Yeah i started with JS .. the first programming lang i taught myself was JS .. 😂 that also nubb

**Comment by httpanand** [comment]
> > The reason I said that I bet there is python is because everyone starts out with python, unless you decided to go js first.
> 
> Yeah i started with JS .. the first programming lang i taught myself was JS .. 😂 that also nubb ..

**Comment by ghost** [comment]
Ok this makes me look creepy.

**Comment by whippingdot** [comment]
It does 

Hey @StringentDev can you add him I don't have access to a computer (well I do but that is for gaming) so I can't really do much.

**Comment by httpanand** [comment]
> It does
> 
> Hey @StringentDev can you add him I don't have access to a computer (well I do but that is for gaming) so I can't really do much.

Yeah Tysm < 3 .. Replit users are increasing day by day and can we make the community active?

**Comment by ghost** [comment]
@whippingdot yeah... I do not have perms to do so.

**Comment by whippingdot** [comment]
oh lol i thought you were mod. I'm so lazy ill make you mod just to do it

**Comment by ghost** [comment]
@whippingdot done.
###### pls don't remove me as I solemnly swear to not abuse the power assigned.

**Comment by httpanand** [comment]
> @whippingdot done.
> 
> ###### pls don't remove me as I solemnly swear to not abuse the power assigned.

yee im in..  tysm @whippingdot @StringentDev

**Comment by whippingdot** [comment]
welcome!

**Comment by httpanand** [comment]
> welcome!

So how can i invite my friends? Is there any workflow set up for that?

**Comment by whippingdot** [comment]
Tell me your friends' replit usernames and github usernames and we will add them. You actually can join teams by yourself anyway so you don't need to tell me their favorite languages and all

**Comment by httpanand** [comment]
> Tell me your friends' replit usernames and github usernames and we will add them. You actually can join teams by yourself anyway so you don't need to tell me their favorite languages and all

Sir , if you add a workflow it would be easier for people to join right ? And also more people will join .. IG

**Comment by whippingdot** [comment]
sir lol. im probably younger than you

also manually adding is pretty nice anyway. If you can come up with a workflow you can tell me, but I think the only way people can invite each other to a github org is if everyone has mod perms.

Also there will be some bad people being invited.

**Comment by httpanand** [comment]
> sir lol. im probably younger than you
> 
> also manually adding is pretty nice anyway. If you can come up with a workflow you can tell me, but I think the only way people can invite each other to a github org is if everyone has mod perms.
> 
> Also there will be some bad people being invited.

Ohk the last point is a crucial one .. and also in programming .. its not the age that determines the position 😀

**Comment by ghost** [comment]
I fully agree with you, It becomes so disappointing when people are shut down based upon their age even though they have massive potential.

**Comment by whippingdot** [comment]
No one is shutting me down so I'm happy 😁

**Comment by ghost** [comment]
@httpanand just to let you know, I invited you to the Reqwester project on replit. (@whippingdot Mutter will use that module)

###### I can see you are a stargazer and just decided that since you are interested to give you role in shaping major version `1` in which currently the major version is `0`

**Comment by httpanand** [comment]
> @httpanand just to let you know, I invited you to the Reqwester project on replit. (@whippingdot Mutter will use that module)
> 
> ###### I can see you are a stargazer and just decided that since you are interested to give you role in shaping major version `1` in which currently the major version is `0`

Oh ok 😀

**Comment by httpanand** [comment]
@whippingdot Dude .. have any plan for revive this org ?

**Comment by whippingdot** [comment]
> @whippingdot Dude .. have any plan for revive this org ?

I am in summer break so yea I can code and build something...but then again I'm with my cousins and might not be active all of the time (like I was inactive for a week). We can start something but no guarantee that it will finish (we actually did start something ask @darkdarcool @Conner1115 )
